### ISSUE TITLE
memory - leaking / is there a way to conditionally include the library?

### ISSUE THREAD

**Issue by johndpope** [remirobert/Dotzu-Objective-c#4]
I have an enterprise app that does initial syncs.
it downloads a bucket load of data > 250mb into sqlite.
it seems this library is causing memory to blow out.  
I want to be able to use it / but not when the app initially syncs. 

in my app delegate I'm using this @import dotzu / @import dotzuObjC

of (bDidSyncAllTables) {
        }else{
          [[Dotzu sharedManager] disable]; // force disable
        }

<img width="1135" alt="screen shot 2017-05-05 at 3 34 55 pm" src="https://cloud.githubusercontent.com/assets/289994/25761532/1b5bf7fa-31a9-11e7-9826-e6dcc86f71e6.png">
<img width="1659" alt="screen shot 2017-05-05 at 3 39 03 pm" src="https://cloud.githubusercontent.com/assets/289994/25761531/1b5a23d0-31a9-11e7-8952-ba60375423ca.png">

is there a way I can stop saving the logs / archive > nsuserdefaults. 
I think this needs a limit.

**Comment by johndpope** [comment]
perhaps this hack could solve problem - then users could over ride the logs to whatever / wherever they like. 

http://stackoverflow.com/questions/27109006/can-you-override-between-extensions-in-swift-or-not-compiler-seems-confused

**Comment by johndpope** [comment]
I tried simply hacking this method to not save to defaults / but did stop crash. ideally - I'd like to conditionally avoid the logging altogether at run time if possible.

**Comment by johndpope** [comment]
would be nice if this was used under the hood https://github.com/CocoaLumberjack/CocoaLumberjack

for most apps - this library works great / just falling over when used with enterprise conditions.

**Comment by johndpope** [comment]
public class Logger: LogGenerator {

    static let shared = Logger()
    private let store = StoreManager<Log>(store: .log)
    private let queue = DispatchQueue(label: "logprint.log.queue")

    var enable: Bool = false // need a way to set this
}

**Comment by johndpope** [comment]
much better
<img width="1672" alt="screen shot 2017-05-05 at 4 19 03 pm" src="https://cloud.githubusercontent.com/assets/289994/25762901/93fa0a8a-31ae-11e7-87fd-7983fc2e6425.png">

**Comment by johndpope** [comment]
I'll try doing some profiling

**Comment by johndpope** [comment]
```swift

public class Logger: LogGenerator {

    public static let shared = Logger()
    public var enable: Bool = false

....



public class LoggerObjc: NSObject {
    
    public static func disable(){
        Logger.shared.enable = false
    }
    public static func enable(){
        Logger.shared.enable = true
    }
```

**Comment by johndpope** [comment]
<img width="1275" alt="screen shot 2017-05-05 at 6 02 39 pm" src="https://cloud.githubusercontent.com/assets/289994/25765880/499c009c-31bd-11e7-8073-227a2e4b61c5.png">
<img width="1519" alt="screen shot 2017-05-05 at 6 03 13 pm" src="https://cloud.githubusercontent.com/assets/289994/25765881/49a45134-31bd-11e7-93d9-9bd05f53d1f5.png">

**Comment by johndpope** [comment]
the good news is that it is correcting if the logging is not so constant. you may need to use a semaphore or delay to throttle the logging.  
 
<img width="1097" alt="screen shot 2017-05-05 at 7 10 14 pm" src="https://cloud.githubusercontent.com/assets/289994/25767371/95af7532-31c6-11e7-96c7-b026968dde8a.png">

**Comment by johndpope** [comment]
you may find that if you were to switch in realm as an optional sub podspec / it may boost performance of logging.

**Comment by johndpope** [comment]
https://github.com/muukii-archive/RealmDefaults

**Comment by remirobert** [comment]
The next direction for Dotzu, is to be able to plug your own plugins. A plugin can be what you want. To Log Bluetooth or location. I am working on it currently but require a lot of time.
I also want to add more settings to the logger.

**Comment by johndpope** [comment]
this maybe better alternative for caching. It's used by Facebook for their asyncdisplaykit examples.  https://github.com/pinterest/PINCache

**Comment by remirobert** [comment]
Yes that's a good recommandation. I really want to use realm. But still I would prefer to don't have any dependencies at all.

**Comment by wwe-johndpope** [comment]
I'm thinking that you could decouple the nsarchiving into a provider class / and then allow people to bring their own. It's only 2 functions / save and read.  Then in comments provide some code to suggest using different provider. The other way to do it is to use symaphore  and set priority to low https://medium.com/swiftly-swift/a-quick-look-at-semaphores-6b7b85233ddb

**Comment by johndpope** [comment]
new logging released last year at WWDC
https://developer.apple.com/videos/play/wwdc2016/721/

<img width="1302" alt="screen shot 2017-05-09 at 1 00 33 pm" src="https://cloud.githubusercontent.com/assets/289994/25862874/8cdb13c8-34b7-11e7-8b37-f29c45e0d392.png">

**Comment by johndpope** [comment]
https://developer.apple.com/library/content/samplecode/Logging/Introduction/Intro.html#//apple_ref/doc/uid/TP40017510


Tried digging through headers for other methods to read the log file. There's some log stream option - but no documentation of inflight logs. 

```

## Viewing Logs

Log messages can be viewed in Xcode's console, in the Console application, or via the `log` tool. To view logs while Paper Company is running in the iOS Simulator, run this behemoth of a command in Terminal: `xcrun simctl spawn booted log stream --level debug --predicate '(subsystem == "com.example.apple-samplecode.Paper-Company-Swift") && (category == "Model")'`. To break down the command:

  - `xcrun simctl spawn booted` requests that the iOS Simulator run a command, in this case the `log` tool. This portion of the command is only necessary when running in the simulator.

  - `log stream` serves to view the live stream of log messages produced by a running application. To view saved logs (after the application has stopped running), use `log show` instead.

  - The `--level debug` option captures all messages logged at a level up to and including debug. (Debug is the most verbose level, so this enables all log messages.)

  - The predicate searches for the subsystem and component used in Paper Company's model (in `APLPaperCompany.m`). The `log` tool fully supports [NSPredicate][2] for filtering logs.

```

**Comment by remirobert** [comment]
@johndpope Thanks for the links, it's very interesting. And I didn't Apple has a API for logging
